CREATE DATABASE Examen
GO

USE Examen
GO

CREATE TABLE Clientes
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Apellidos VARCHAR(512) NOT NULL,
	Direccion VARCHAR(512) NOT NULL,
)
GO

CREATE TABLE Tiendas
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Sucursal VARCHAR(100) NOT NULL,
	Direccion VARCHAR(512) NOT NULL	
)
GO

CREATE TABLE Articulos
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Codigo INT NOT NULL,
	Descripcion VARCHAR(512) NOT NULL,
	Precio DECIMAL(18,2) NOT NULL,
	Stock INT NOT NULL
)
GO

CREATE TABLE ArticuloTienda
(
	ArticuloId INT NOT NULL,
	TiendaId INT NOT NULL,
	Fecha DateTime NOT NULL
	CONSTRAINT FK_AT_Articulo
	FOREIGN KEY(ArticuloId) REFERENCES Articulos(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_AT_Tienda
	FOREIGN KEY(TiendaId) REFERENCES Tiendas(Id) ON UPDATE CASCADE ON DELETE CASCADE
)
GO

CREATE TABLE ClienteArticulo
(
	ClienteId INT NOT NULL,
	ArticuloId INT NOT NULL,
	Fecha DateTime NOT NULL,
	CONSTRAINT FK_CA_Cliente
	FOREIGN KEY(ClienteId) REFERENCES Clientes(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_CA_Articulo
	FOREIGN KEY(ArticuloId) REFERENCES Articulos(Id) ON UPDATE CASCADE ON DELETE CASCADE
)
GO